# Generated by Django 4.0.3 on 2022-03-29 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('excited', 'Excited'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('bored', 'Bored'), ('Sad', 'Sad'), ('Angry', 'Angry')], max_length=20)),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Cloudy', 'Cloudy'), ('Snowy', 'Snowy'), ('Windy', 'Windy')], max_length=20)),
                ('health', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick')], max_length=20)),
                ('activities', models.CharField(choices=[('Work', 'Work'), ('Free', 'Free')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
