# Generated by Django 4.0.3 on 2022-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodregistry', '0003_rename_activities_personmood_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmood',
            name='mood',
            field=models.CharField(choices=[('Excited', 'Excited'), ('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Bored', 'Bored'), ('Sad', 'Sad'), ('Angry', 'Angry')], max_length=20),
        ),
    ]
