# Generated by Django 4.0.3 on 2022-05-02 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodregistry', '0004_alter_personmood_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmood',
            name='mood_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
