# Generated by Django 4.0.3 on 2022-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodregistry', '0005_personmood_mood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmood',
            name='note',
            field=models.TextField(default='A note about mood', max_length=200),
            preserve_default=False,
        ),
    ]
