# Generated by Django 4.0.3 on 2022-11-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodregistry', '0006_personmood_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmood',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
